<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>p</string>
		<string>ph</string>
		<string>P</string>
		<string>PH</string>
	</array>
	<key>name</key>
	<string>TI PRUv2 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\#\s*if\s+0\b</string>
			<key>end</key>
			<string>^\s*\#\s*endif\b</string>
			<key>name</key>
			<string>comment.preprocessor</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#\s*(include|import)\b\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>meta.preprocessor.c.include</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.c</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.c</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.c</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.include.c</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.c</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.c</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.lt-gt.include.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#\s*(define|defined|elif|else|if|ifdef|ifndef|line|pragma|undef|endif)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>meta.preprocessor.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(adc|add|sub|suc|rsb|rsc|lsl|lsr|and|or|xor|not|min|max|clr|set|scan|lmbd|mov|mov32|ldi|lbbo|sbbo|lbco|sbco|lfc|stc|zero|mvib|mviw|mvid|jmp|jal|call|ret|qbgt|qbge|qblt|qble|qbeq|qbne|qba|qbbs|qbbc|wbs|wbc|halt|slp|adc|add|sub|suc|rsb|rsc|lsl|lsr|and|or|xor|not|min|max|clr|set|scan|lmbd|mov|ldi|lbbo|sbbo|lbco|sbco|lfc|stc|zero|mvib|mviw|mvid|jmp|jal|call|ret|qbgt|qbge|qblt|qble|qbeq|qbne|qba|qbbs|qbbc|wbs|wbc|halt|slp|ADC|ADD|SUB|SUC|RSB|RSC|LSL|LSR|AND|OR|XOR|NOT|MIN|MAX|CLR|SET|SCAN|LMBD|MOV|MOV32|LDI|LBBO|SBBO|LBCO|SBCO|LFC|STC|ZERO|MVIB|MVIW|MVID|JMP|JAL|CALL|RET|QBGT|QBGE|QBLT|QBLE|QBEQ|QBNE|QBA|QBBS|QBBC|WBS|WBC|HALT|SLP)(l|w|b)?\b</string>
			<key>name</key>
			<string>keyword.mnemonic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\S+:</string>
			<key>name</key>
			<string>entity.name.class</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[0-9a-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.literal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9a-f]+h?\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(entrypoint|origin|main|end|proc|ret|struct|ends|u8|u16|u32|assign|setcallreg|macro|mparam|endm|codeword|enter|leave|using)</string>
			<key>name</key>
			<string>entity.name.class</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(r[0-9]|r1[0-9]|r2[0-9]|r3[0-1]|r[0-9]\.w[0-1]|r1[0-9]\.w[0-1]|r2[0-9]\.w[0-1]|r3[0-1]\.w[0-1])+\b</string>
			<key>name</key>
			<string>storage.register</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.tipruv2</string>
	<key>uuid</key>
	<string>D3AB02DA-DB86-4573-B4D1-772ABA163C24</string>
</dict>
</plist>
